name: Build_CI_Dev

on:
  pull_request:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - "**/README.md"
      - "**/dependabot.yml"
    branches:
      - develop

concurrency: develop_CI

jobs:
  build-ci:
    name: "Build and CI Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version-file: "Javascript/.nvmrc"
      - name: Test Node.js
        run: |
          cd Javascript && npm ci && npm test

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Test Python
        run: |
          cd Python && pip install -r requirements.txt && pytest **/*_test.py

  automerge:
    needs: build-ci
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.9
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
